### ISSUE TITLE
Event Espresso 4.12 coffee Icon and Item displayed on Dashboard menu after a page refresh.

### ISSUE THREAD

**Issue by joaovictorangeline** [eventespresso/event-espresso-core#3816] opened 2022-04-28 20:06 UTC
**Describe the bug**
When Event Espresso v4.12 is activated, the "Event Espresso" coffee icon and item on Dashboard menu are displayed after the page is refreshed.

**To Reproduce**

**Expected behavior**
It should appear on the Dashboard left menu and with the coffee icon immediately after it's activated.

**Screenshots**
![image](https://user-images.githubusercontent.com/102395051/165836480-7105e2d5-13e7-4b0f-a230-a198e31c84ab.png)

**Environment:**
 - Version of Event Espresso:  v4.12
 - Version of WordPress: 5.9.3
 - Browser Chrome Version 100.0.4896.127 (Official Build) (arm64)
 - PHP Version 7.4.1

**Comment by tn3rb** [comment] 2022-05-05 02:35
duplicate of #3776

**Closed by tn3rb** 2022-05-05 02:35 UTC
