### ISSUE TITLE
Custom Message Template Pack for "Batch"/Newsletter Type not working

### ISSUE THREAD

**Issue by ARAGATO** [eventespresso/event-espresso-core#200] opened 2017-01-31 07:07 UTC
### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
EE Core, Messages

### What version of WordPress is on the site this issue happened?
4.7.2

### Outline the steps to reproduce
Create Message Template Pack, add Message type "newsletter", custom templates are not pulled

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
**Message type:** http://uploads.aragato-server.net/screenshots/20170127b625ab186b.png
**Added "newsletter":** http://uploads.aragato-server.net/screenshots/20170131ca1efdcdd9.png
**Message Pack is found, but default is gone:** http://uploads.aragato-server.net/screenshots/201701289330c0f6e9.png
**Custom templates are not pulled, but only the original ones:** http://uploads.aragato-server.net/screenshots/2017012823d51e6cd4.png

**Comment by nerrad** [comment] 2017-01-31 13:47
Thanks for your report I'll look into this when I can (hopefully this week).

**Comment by nerrad** [comment] 2017-01-31 14:56
Hi there, I did some testing using the [template pack example provided in the tests folder](https://github.com/eventespresso/event-espresso-core/tree/master/tests/mocks/addons/new-messages-template-pack) and its behaving as expected for me.  

At this point, based on the information available to me from  your post, it looks like it may be problem in the code with the custom template pack you are building.  Have you read this [documentation](https://github.com/eventespresso/event-espresso-core/blob/master/docs/E--Messages-System/overview-message-template-packs-variations.md) or [this](https://github.com/eventespresso/event-espresso-core/blob/master/docs/E--Messages-System/registering-message-template-packs.md)?  Are you able to share the code for the actual template pack you are attempting to build? 

At this point there's not a way for me to reproduce (and thus fix) the bug you are reporting.

**Comment by nerrad** [comment] 2017-01-31 15:07
I asked around the EE team and they pointed me to your [original support post in our forums](https://eventespresso.com/topic/register-message-type-batch-for-new-message-template-pack/).  I was able to get more information from that post about what you are attempting to do.  So I was able to reproduce the issue, I'm investigating now.

**Comment by nerrad** [comment] 2017-01-31 15:22
Internal ticket for reference: https://events.codebasehq.com/projects/event-espresso/tickets/10441

**Comment by nerrad** [comment] 2017-01-31 21:00
Hi there, this issue has been fixed and is currently receiving a code review.  If you want to get a head start on testing it you can check out the [related_branch](https://github.com/eventespresso/event-espresso-core/tree/BUG-10441-fix-registering-default-supports-for-message-types).

I'll try to remember to update this issue when this gets merged to master.

**Comment by ARAGATO** [comment] 2017-02-01 06:08
Great, thanks. I will wait for the master to be released.

**Closed** 2017-02-01 06:08 UTC
Labels: bug, messages

**Comment by nerrad** [comment] 2017-02-03 12:20
Just a heads up that the work done for this issue has been merged to master so it'll be in the next release of EE.
