### ISSUE TITLE
Payment Method

### ISSUE THREAD

**Issue by xyluz** [eventespresso/event-espresso-core#233] opened 2017-06-12 10:21 UTC
Hi, i am trying to create a payment method (for interswitch), i am having trouble with updating the payment status... it always comes back pending. 

What do you suggest i do?

**Comment by nerrad** [comment] 2017-06-12 10:57
Hi there, have you read through the documentation located at https://github.com/eventespresso/event-espresso-core/tree/master/docs/L--Payment-Methods-and-Gateways ?

You have not given enough information to assist you.  What type of payment method are you creating for Interswitch?  Onsite?  Offsite?

**Comment by xyluz** [comment] 2017-06-12 12:30
hi.

I am creating an offsite payment for now. 

Yes, i have read the link, i still can't seem to figure it out.. let me explain better:

1. Interswitch provides unique values depending on their customer, i want whoever wants to use the plugin to be able to supply these values in the settings. (Right now I hard-coded the values in).
2. I am unable to get the user details to send to interswitch, I am working with the new payment method "skeleton" provided, and in "set_redirection_info" i need to send the user details to interswitch, that's the details filled while registering. I have been unable to do this (values are also hard coded right now)
3. On payment attempt, interswitch has a lot of response code, and I need to consider each... I print_r($transaction) and I see the response code, but on trying to update the database and display result to use, that doesn't work... it displays pending every time. 

Those are the 3 main issues I am having for the offsite integration.

**Comment by mnelson4** [comment] 2017-06-12 17:20
1. You should add a field to the settings page. I assume the payment method class (the class that primarily talks with the rest of EE) is called `EE_PMT_Interswitch`. Change `EE_PMT_Interswitch::generate_new_settings_form()`, and add another field to the `EE_Payment_Method_Form`'s "extra_meta_inputs". See https://github.com/eventespresso/event-espresso-core/blob/master/docs/J--EE4-Forms-System/ee-forms-system-overview.md. Let's assume you added a field named `unique_value` to the form. It will now appear on the settings page, and EE will take care of saving the user's input for you. 
Also, you should add a property on the gateway class (the class that primarily talks with the gateway server), which is probably named `EEG_Interswitch`, named `_unique_value`.  This property will automatically be populated with the value the user set in the settings page.
2. So let's assume you want the registration's first name and email. Inside `EEG_Interswitch::set_redirection_info()`, the argument receives a `$payment` object, which is an instance of `EE_Payment`. Here is some code to get that data:
```
$primary_attendee = $payment->get_primary_attendee();
/* @var $primary_attendee EE_Attendee */
$first_name = $primary_attendee->fname();
$email = $primary_attendee->email();
```
3. Inside `EEG_Interswitch::handle_payment_update()`, all you need to do is return an object of instance `EE_Payment`, and call `set_status()` on it, with either the values "PAP" (approved), "PPN" (pending",  "PDC" (declined), or "PFL" (failed). You shouldn't need to try to save anything to the database or display anything to the screen here, EE core code will take care of that based on what you set the payment status to.

Do these suggestions help?

**Comment by xyluz** [comment] 2017-06-12 17:24
Yes, very much.
I'll try them out and get back to you shortly. 
Thank you.

**Comment by xyluz** [comment] 2017-06-13 14:54
hi. thanks.

I am getting closer.

here's the object i am returning: `EE_Payment Object
(
    [_props_n_values_provided_in_constructor:protected] => Array
        (
            [PAY_ID] => 3
            [TXN_ID] => 62
            [STS_ID] => PAP
            [PAY_timestamp] => 2017-05-23 01:29:58
            [PAY_source] => CART
            [PAY_amount] => 35000.000
            [PMD_ID] => 10
            [PAY_gateway_response] => Payment Approved
            [PAY_txn_id_chq_nmbr] => 
            [PAY_po_number] => 
            [PAY_extra_accntng] => 
            [PAY_details] => 
            [PAY_redirect_url] => 
            [PAY_redirect_args] => 
        )`
(part of the object), it clearly states that the transaction was sucessful.
But on my success page, it still stays payment pending.

Please do you know why?

**Comment by mnelson4** [comment] 2017-06-13 18:27
Ya that looks good.
Is Interswitch sending a separate IPN request to the server, or is the user returning from Interswitch with their payment information? If they're sending a separate IPN, did you set the property `_uses_separate_IPN_request` on the gateway class (see https://github.com/eventespresso/event-espresso-core/blob/master/docs/L--Payment-Methods-and-Gateways/gateway-classes.md#handle_payment_update)
If you are already doing that, you may want to provide us with your actual code implementation

**Comment by xyluz** [comment] 2017-06-13 18:40
The user returns with their payment information.

**Comment by mnelson4** [comment] 2017-06-13 20:55
Ya ok, so what you're doing sounds right. If you want any more help I'll need to look at the actual code. A link to a github repo would be ideal

**Comment by xyluz** [comment] 2017-06-13 21:25
https://github.com/xyluz/event-espresso-interswitch
thanks so much.

**Comment by mnelson4** [comment] 2017-06-13 22:37
currently, your `handle_payment_update` method calls `exit;`, which I assume is just debug code. But before you added that, were you calling `return $payment;`? If not, that would explain things

**Comment by mnelson4** [comment] 2017-06-13 22:40
also, you can probably remove all the `override_use_separate_IPN_request` references in the code. That was mostly just useful for the payment method skeleton, to show an offsite payment method can either handle IPN data either in the same request, or in a separate request (but I'm starting to see it's probably mostly just confusing).

**Comment by xyluz** [comment] 2017-06-14 04:31
yes, I was returning it. you are right, the exit is just for debugging, i wouldn't be able to see the actual object being returned if I don't exit.

okay, I'll remove the IPN reference.

so, have you been able to determine the problem?

**Comment by mnelson4** [comment] 2017-06-14 17:36
No, I don't see what's wrong. If you provide me with an actual working add-on I can debug it further (eg the exact files I would upload to my wp-content/plugins folder in order to run the gateway).

**Comment by xyluz** [comment] 2017-06-14 18:21
Okay, done. i updated the repo.

**Comment by mnelson4** [comment] 2017-06-14 20:11
Ok good, but what is with this file: https://github.com/xyluz/event-espresso-interswitch/blob/master/event-espresso-interswitch/payment_methods/Interswitch_Offsite/EEG_Interswitch_Offsite.gateway___.php ? That seems to be the more up-to-date version, but EE won't find that. 
Can you please double-check that add-on is exactly what you're using to reproduce the issue? Also, did removing the usage `override_use_separate_IPN_request` resolve the problem? (You only said you made that change, but didn't indicate if it fixed anything or not)

**Comment by xyluz** [comment] 2017-06-21 08:19
Hi. I have been away for sometime. 

Please ignore the weird files (lol). No, removing the usage override_use_separate_IPN_request did not resolve the issue.

Can you help proffer another solution?

**Comment by xyluz** [comment] 2017-06-23 02:50
hi, i still need help with this.

**Comment by nerrad** [comment] 2017-06-23 13:34
Hi there,

We try to assist developers building add-ons and payment methods for the Event Espresso plugin where we can and as we have time, but counting on us to respond quickly to third party developers "urgent" timelines is not generally a good idea.  We prioritize working on bugs and features as a part of our own roadmap as determined in part by what many of our customers with paid support license have requested.

Mike (one of the developers on our team most familiar with the payment method system) has been trying to assist you here where he can but he's currently on vacation so I would not expect further response soon.

In the future, its also a good idea, before commenting that something is urgent, you take a look at the timeline of posts in a thread.  Mike wrote in here almost 9 days ago before your most recent reply.  If it was "urgent" why did you wait so long to post again in here?

**Comment by xyluz** [comment] 2017-06-23 13:36
Okay. I understand. Thank you for your response.

**Comment by mnelson4** [comment] 2017-06-29 21:34
hi @xyluz I had a chance to try your code. Upon returning from interswitch, I got this error:


> Notice: Undefined index: gateway_txn_id in /srv/www/wordpress-develop/src/wp-content/plugins/eea-interswitch/payment_methods/Interswitch_Offsite/EEG_Interswitch_Offsite.gateway.php on line 64

> Fatal error: Call to a member function set_status() on a non-object in /srv/www/wordpress-develop/src/wp-content/plugins/eea-interswitch/payment_methods/Interswitch_Offsite/EEG_Interswitch_Offsite.gateway.php on line 69

Are you sure you were using the same code? If so, my guess is that your code was grabbing the wrong payment, and then updating it; however, the payment related to the transaction was still pending payment.

I created a pull request which addresses the issue: https://github.com/xyluz/event-espresso-interswitch/pull/1.

There are still a number of issues, the main one being that it seems you hard-coded the gateway credentials in the repo instead of using the user's input. You can look at any of our other payment methods (either the ones in https://github.com/eventespresso/event-espresso-core/tree/master/payment_methods , or one of our add-on payment methods like https://github.com/eventespresso/eea-chase-orbital or https://github.com/eventespresso/eea-vanco-pm). 

Also, in one spot in your code you're comparing a string from the interswitch to a constant `Z6`, although no such constant has been defined. See https://github.com/xyluz/event-espresso-interswitch/blob/master/event-espresso-interswitch/payment_methods/Interswitch_Offsite/EEG_Interswitch_Offsite.gateway.php#L82. Did you meant to compare it to the string `'Z6'`? eg `else if($update_info[ 'resp' ] == 'Z6'){`?

So once you have that addressed, your payment method is looking pretty good.

Also, @xyluz helping you debug the problems in your code has taken quite a lot longer than I anticipated. We'd appreciate if you'd at least leave some positive feedback on https://wordpress.org/support/plugin/event-espresso-decaf/reviews/#new-post.

Thanks, closing for now seeing how my pull request seems to have resolved the issue

**Closed by mnelson4** 2017-06-29 21:34 UTC
Labels: gateways, question

**Comment by xyluz** [comment] 2017-06-30 07:31
Okay. Thank you. I'll leave a review.
