### ISSUE TITLE
PHP Deprecated notice on plugin activation

### ISSUE THREAD

**Issue by sumobi** [eventespresso/event-espresso-core#79] opened 2015-06-05 01:23 UTC
In case you weren't aware, the following message shows on plugin activation:

PHP Deprecated:  EE_Error::add_error() was called <strong>incorrectly</strong>. You need to provide the file name, function name, and line number that the error occurred on in order to better assist with debugging. (This message was added in version 4.6.31.rc.014 of Event Espresso. in /wp-content/plugins/event-espresso-core/core/helpers/EEH_Debug_Tools.helper.php on line 274

Master branch

**Comment by nerrad** [comment] 2015-06-05 02:14
Thanks for reporting this.   Need a little more info:

1. Any other EE addons installed and active?
2. Was this a fresh activation?

**Comment by sumobi** [comment] 2015-06-05 02:27
@nerrad Sure thing, just EE on a fresh site of a MS installation, nothing else active

**Comment by nerrad** [comment] 2015-06-05 02:30
thanks!  Really appreciate the reports you've made recently, always great to have fresh eyes on things.

**Comment by sumobi** [comment] 2015-06-05 02:36
@nerrad You're welcome! It's always great to sit down and play with some else's plugin. We're hoping to build an EE integration for AffiliateWP.

**Comment by nerrad** [comment] 2015-06-05 02:40
> We're hoping to build an EE integration for AffiliateWP.

That's awesome!  Definitely let us know if you have any questions about that :)

**Comment by tn3rb** [comment] 2015-08-10 15:56
@nerrad 
was this issue ever found in core? And is there a corresponding Codebase ticket?
I'm assuming it's within the MS addon.

**Comment by nerrad** [comment] 2015-08-10 16:05
I never tried to reproduce.  I don't think this involves the multi-site add-on because that isn't publicly released and this report outlines it just happened on core.

**Comment by mnelson4** [comment] 2015-08-10 17:01
hey I just looked at `EEH_Debug_Tools.helper.php` line 278 and `EE_Error:add_error` is indeed being called WITHOUT the file, function and line parameters. I'll create a ticket and ask @sumobi to verify it resolves the issue ( @tn3rb feel free to take back if you like)

**Comment by mnelson4** [comment] 2015-08-10 17:07
kk @sumobi can you try branch https://github.com/eventespresso/event-espresso-core/tree/BUG-8631-EE_Error-add_error-called-incorrectly-from-EEH_Debug_Tools to see if it removes the error for you on plugin activation? 
Note: the error you saw was generating while trying to tell you about some OTHER error. So this fix will probably reveal what the other error was (so expect there to be another error message!)

**Comment by mnelson4** [comment] 2015-08-24 19:09
our support guys got around to testing this as well and it was merged into 4.8.0 and released. It just would have been nice to have confirmation from you that it was resolved.

**Closed by mnelson4** 2015-08-24 19:09 UTC
Labels: bug, needs testing
