### ISSUE TITLE
Fatal when in maintenance mode

### ISSUE THREAD

**Issue by knazart** [eventespresso/event-espresso-core#3802] opened 2022-04-13 14:42 UTC
`dev` branch.

There is a front-end fatal when EE is in lvl2 maintenance mode:

```
PHP Fatal error:  Uncaught RuntimeException: Invalid arguments supplied for the EE_Front_Controller class, 3 were required but 0 were passed. in /srv/www/plugins.test/public_html/wp-content/plugins/event-espresso-core/core/EE_Registry.core.php:1276
```

**Comment by tn3rb** [comment] 2022-05-05 02:34
duplicate of #3779

**Closed by tn3rb** 2022-05-05 02:34 UTC
