### ISSUE TITLE
WP User Integration add-on attendee/user connections

### ISSUE THREAD

**Issue by KinnaT** [eventespresso/event-espresso-core#175] opened 2016-11-22 20:24 UTC
### Is this a bug report?

* [x] yes
* [ ] no

### What branch did this occur in?
Master

### What version of WordPress is on the site this issue happened?
4.6.1

The WP User Integration add-on on my single site install has never let admins create registrations for users correctly. When doing a manual registration in wp-admin, the newly-registered contact/attendee doesn’t link to the user. It only creates a link and the entry for `EE_Attendee_ID` in the usermeta table if you’re registering for an event on the front-end while logged in as that user. The User Switching plugin is a usable workaround, but is cumbersome.

If I make the changes [listed here](https://github.com/KinnaT/event-espresso-addons/tree/master/eea-wp-user-integration), manually registering someone on the back end makes the link between attendee and WP user regardless of whether the attendee or user is created first.
With this, an admin registering a random user can input the first/last name and email when using the Add New Registration and the contact created for them is then linked to the user. (A View Linked Contact button shows on the User edit page and a WordPress User Profile link shows on the Contact edit page.)

`get_user_option` and `update_user_option` should work on single site installs, but they don’t for me with this add-on. I believe that `get_user_meta` and `update_user_meta` don't work correctly on multisite installs though?

[EE forum support post for reference](https://eventespresso.com/topic/wp-user-integration-attendeeuser-connections/)

Also, is there a separate repo for the add-ons?

**Comment by nerrad** [comment] 2016-11-22 20:43
Hi there,

Thanks for taking the time to write your issue and provide this feedback!

The main reason why we have not implemented linking user to attendee via admin side registrations is because there is no _foolproof_ way (yet) to indicate WHAT user the contact should be linked to.  You have suggested using first_name, last_name, and email address, but the problem is that as a distributed product, that's not always going to be a valid method to "match" a registration with a user.

We have talked internally about adding some ui for providing a username to link the registration with (if there isn't already a link) but that's still something needing explored and we don't want to rush it.  Currently it is not something [in our roadmap](https://trello.com/b/zg9DCIpe/event-espresso-public-roadmap) because of other highly requested things requested by our users.

What I recommend is seeing if you can accomplish what you need to do using existing hooks and filters.  If that is not possible with _existing_ hooks and filters, then a quicker win would be for you to suggest places where having a filter and/or action hook would help you implement what you need.

Regarding changing `*_user_option` to `*_user_meta`:  That is not something we will be doing in the core code. `*_user_option` is something we _must_ implement in order to be multi-site compatible and it will remain single-site compatible.  It's not clear to me why its not "working" in your case.

Regarding a repo for the add-on.  Yes we have a private github repo for this.  I'll see if its possible to grant you access to it, I'll post back in here if we do.

For now, I'm going to close this issue because its not really an EE core ticket.  However feel free to continue the conversation in it as necessary.

**Closed by nerrad** 2016-11-22 20:43 UTC
Labels: question

**Comment by nerrad** [comment] 2016-11-22 20:51
I invited you to the private repo.  So you should be able to access it (read only) once you've accepted the invitation.  Please continue the conversation there (you can link to this issue if you want).

**Comment by nerrad** [comment] 2016-11-22 20:59
It turns out that there's already an item on our roadmap that outlines a solution for admin side registrations (which is more along the lines of what we'd likely end up implementing once we get to it): https://trello.com/c/3qDvvRgG/113-wp-user-integration-admin-side-registrations-add-ajaxified-text-field-that-autofills-for-existing-user-accounts
