### ISSUE TITLE
BUG: Call to member function on non-object.

### ISSUE THREAD

**Issue by thebeline** [eventespresso/event-espresso-core#192] opened 2016-12-22 18:21 UTC
This may not be much help, but:

https://github.com/eventespresso/event-espresso-core/blob/master/modules/single_page_checkout/EED_Single_Page_Checkout.module.php#L1413

Threw a 500 error on the payment page after the PayPal API failed (for unknown reasons).  I got a message back saying there was some error, so I fixed my credentials, and clicked PayPal again, and "Finalize Payment" and suddenly, 500 Error.

```
PHP message: PHP Fatal error:  Call to a member function enqueue_js() on a non-object
```

**Comment by nerrad** [comment] 2016-12-22 18:42
Do you have a stack trace that directed you to that specific line you linked to or is that just a guess?

**Comment by thebeline** [comment] 2016-12-22 18:49
```
2016/12/22 13:14:17 [error] 12508#0: *26487 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function enqueue_js() on a non-object in /var/www/clients/client5/web26/web/wp-content/plugins/event-espresso-core-reg/modules/single_page_checkout/EED_Single_Page_Checkout.module.php on line 1406" while reading response header from upstream, client: XXX, server: events.thomaspointbeach.com, request: "GET /registration-checkout/?uts=1482429879&step=payment_options&action=redirect_form HTTP/1.1", upstream: "fastcgi://127.0.0.1:9035", host: "events.thomaspointbeach.com"
```

**Comment by mnelson4** [comment] 2016-12-23 18:42
yeah I'm actually able to reproduce this. The ajax request sent from SPCO needs to have some kind of fatal error (so that's the first problem), but then SPCO doesn't recover very well from this. It looks like it does (because you're able to try paying again) but instead of sending another ajax request, it submits a post (not sure where) and you get the above-mentioned fatal error.
I'm creating a ticket in codebase for brent to look into this. I'll reference this ticket there

**Comment by mnelson4** [comment] 2016-12-23 18:47
Because this fatal error only comes up after you've already had a fatal error during the previous request, I don't think this is going to be prioritized too highly. But we'll try to get it fixed

**Comment by tn3rb** [comment] 2016-12-31 17:04
if you are interested, feel free to test out the fix that is in this branch on your development site:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10334-spco-enqueue-js

**Comment by tn3rb** [comment] 2017-02-07 22:43
that branch was merged to master, so I'm going to close this ticket.

**Closed by tn3rb** 2017-02-07 22:43 UTC
Labels: bug
