### ISSUE TITLE
Seemingly random no data is saved to a registration

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#130] opened 2015-11-13 14:58 UTC
Hi!

I've got a client using EE here: kfsk.se/blog/kurs-konferens

They've got an issue where sometimes not all information is saved. To be more precise the system questions are empty (firstname, lastname, email etc.) while all extra questions still gets saved. 

I've done a bit of testing (no massive unit tests just random submissions from different browsers and OS) but haven't been able to locate the error. 

Here's the raw info of the server/setup:
**redacted, we'll keep this info out of the public view, okay?**

They are not running the very latest but this issue has been there for quite some time (not sure how long or if it's been there since the beginning). Unless you've actually worked on something like this on some of the very latest releases I don't think it matters (I've checked the logs). 

I should probably also note that they are *not* using any payments. The payment step has been completely removed with this code (got it from one of your gists):
`
//Completely remove the payment options stage of EE checkout
function jf_ee_remove_payment_step( $reg_steps ) {
    foreach( $reg_steps as $step => $value ){
        if( $value['slug'] == 'payment_options' ) {
            unset( $reg_steps[$step] );
        }
    }
    return $reg_steps;
}
add_filter ( 'AHEE__SPCO__load_reg_steps__reg_steps_to_load', 'jf_ee_remove_payment_step' );
`

Very grateful for insight and help!

**Comment by mnelson4** [comment] 2015-11-13 17:36
>  To be more precise the system questions are empty (firstname, lastname, email etc.) while all extra questions still gets saved.

Where do you see the system questions are empty? FYI for a while now, answers to system questions are stored in the esp_attendee_meta table's rows, NOT in the esp_answer table like all custom questions are.

**Comment by jonathan-dejong** [comment] 2015-11-14 09:42
The system questions answers are empty everywhere in admin. So it's not some custom output. The client is pretty quick in finding the persons and filling in the missing information so I haven't had a chance to check the esp_attendee_meta table when this has happened but I would assume they're empty :)

**Comment by mnelson4** [comment] 2015-11-16 15:11
> I would assume they're empty :)

yeah they probably are. Can you please confirm that? Because it's possible the data IS getting saved but not being displayed. Or it's possible the system question data is getting saved to the `esp_answer` table (erroneously, because it should be in the `ep_attendee_meta` table) and so not being displayed. It would be helpful to know which.

Also, is this a problem only when using that code snippet which removes the payment step? Ie, if the payment step is shown again, does the problem go away? Or might there be another plugin interfering?

**Comment by jonathan-dejong** [comment] 2015-11-17 14:26
Hi Nelson,

I'm gonna see if I can check the different tables. 
As for payment step or not it's hard for me to test it.. I do have a dev site where I can enable payment step but it seems to happen so randomly so it's possible I could go through any number of registrations before anything would happen.. I can't really do 50+ registrations manually :) 
(This is where I should have learned better unit testing). 

I will try some on my dev site with the payment step disabled just to see if I can recreate the error myself and maintain the data (or lack thereof). Then if I can reproduce the error I'll enable payment and try again. 


They also just had an error where 5 people signed up to an event, got the confirmation email but wasn't registered in the DB.. I got one of their registration codes and did a search in the REG_code column in esp_registrations but found no match. So it really seems the registrations wasn't even saved??

**Comment by jonathan-dejong** [comment] 2015-11-17 20:06
Alright so I've found a registration that's been made on the live site.
The only value saved to esp_attendee_meta is the users email. 

I searched for the ATT_ID in esp_registrations but there was none. Which means there's no REG_ID I can check against in esp_answers. 

Here's some screenshots:
<img width="532" alt="esp_registrations" src="https://cloud.githubusercontent.com/assets/1508751/11223067/3d94adf2-8d6e-11e5-8376-e06820202f5e.png">
<img width="1187" alt="esp_attendee_meta" src="https://cloud.githubusercontent.com/assets/1508751/11223066/3d910a76-8d6e-11e5-8f5e-b058f908e9ca.png">

Regarding your question about plugins.. I have some custom built plugins but they are only for fetching info like a custom CSV exporter plugin for EE etc. 

There is one plugin which is basically a copy of your wp user addon with some modifications to sync all attendee info to the actual WP user. Not just connect registrations to the wp user. 
Here's a zip of the plugin.
https://www.dropbox.com/s/3xarz485r6ndg29/ee-wpuser-custom.zip?dl=0

I don't know to what extend you're able to help me. I'd be very happy if you'd be able to take a look at the plugin. If you think this needs extended support I'm willing to discuss payed support beyond being a customer :)  This is a make or break thing for the client and none of us want to start over with a lesser plugin.

**Comment by mnelson4** [comment] 2015-11-17 22:34
> They also just had an error where 5 people signed up to an event, got the confirmation email but wasn't registered in the DB

do you have a copy of the email they received in this case? (Usually the site admin is CC'd)

I wonder if the requests are just timing out, and so not all the information is getting saved. In this case giving the server some more resources would help

**Comment by mnelson4** [comment] 2015-11-17 22:48
I took a look at your plugin. I think it's probably good, but it adds a bit more processing time. 
Also you mentioned the error where 5 people signed up for an event, the confirmation email was sent but the registrations weren't saved to the db. That supports my suspicion that the server is just timing out, because when 5 people signup, and we send emails for the 5 users, and admin etc, that can take quite a bit of time.
Can you increase the timeout on your server? You could also try disabling some of the messages, or using a plugin like our Postmark App & Mandrill Transactional Email Handling plugin, which offloads lots of the work of sending emails from your server to the associated webservice.

**Comment by jonathan-dejong** [comment] 2015-11-18 09:20
Hmmm that's a good guess I think.. I'm gonna have a look att the timeout of the server. It's a custom server on Microsoft Azure so it shouldn't be a problem increasing timeout. 

Here's a screenshot of the email one of the registrants received. What I find really odd is that they get a registration code but it does not exist in DB. The reason it looks completely messed up is probably because it's been sent through to me after like 3-4 forwards. 

<img width="650" alt="email" src="https://cloud.githubusercontent.com/assets/1508751/11237095/faa28044-8ddd-11e5-90e6-0f863cf223c6.png">

**Comment by jonathan-dejong** [comment] 2015-11-18 11:32
Btw, Is it really possible that a timeout allows for emails to be sent but the registration isn't saved? 
Seems a bit backwards :)

**Comment by nerrad** [comment] 2015-11-18 14:43
Jonathan, is your dev site running in a Microsoft Azure environment.  If you're unable to reproduce then that points to it possibly being an environment issue.  What's the setup in the Azure server, are they running a Windows OS or Linux in a VM?

We haven't had much luck with windows based setups (hence why we don't support EE running on Windows based servers), there's just too many hard to troubleshoot issues that pop up.

**Comment by jonathan-dejong** [comment] 2015-11-18 14:50
My dev site is local running in Vagrant (ubuntu).

They are running Linux in a VM. I tried to talk the client out of Azure from the very beginning but they insisted since they have everything in that license. The clients tech-guy is an old serverguy who also claims there is no difference in running linux as VM on an azure server compared to just running a pure Linux server outside of azure. Myself I'm not really a server guy so I can't say much on the subject. 

If there's a way I can send files to you privately I can send a PDF of the phpinfo from the server?

**Comment by nerrad** [comment] 2015-11-18 15:00
Yeah I don't have much experience working with Azure but if Linux is running in the VM that *should* be okay.

As Mike suggested I think your first step is to see if its a timeout issue.   As for emails being sent but registrations not being saved not sure what would be going on.  How is this server setup?  Is mysql and php all running on the same box?  is mysql  being replicated so there is a master/slave?  Is the web server apache or nginx?  Is there any caching involved (object or otherwise)?

**Comment by joshfeck** [comment] 2015-11-18 15:08
We've seen issues like this one before and the solution ended up being they set up either the Postmark App or Mandrill Transactional Email Handling plugin to off-load the notification/email processing.

**Comment by jonathan-dejong** [comment] 2015-11-18 17:00
Yeah php, mysql etc. is running in the same box. 
For emails they're using an external service already called sendgrid.net.
We're setting the SMTP server in wp-config using https://wordpress.org/plugins/global-smtp/

The problem is I don't know how to check wether this is a timeout issue. We've increased timeout, memory limit etc. on the server. I suppose the only way to try it is to setup a private event and start registering dummy attendees on my own?

**Comment by jonathan-dejong** [comment] 2015-11-19 18:44
@joshfeck For what reason would it be solved with an email handling plugin? Isn't the issue that the emails are being sent out before making certain a registration is saved to DB?

**Comment by mnelson4** [comment] 2015-11-19 19:50
I think the email handling plugin would help with timeouts, if that's the issue.
But yeah, the email being sent out, with no registrations in the system, is quite puzzling. It might be a completely different issue.

It's possible that this might be an issue which was resolved in 4.8.11, where sometimes transactions would be accidentally cleaned up when they were in the middle of registering. See http://eventespresso.com/wiki/ee4-changelog/
>Record when line items are created, and don't delete line items which are younger than a specified cutoff time (by default the same as transactions, a week).

What version of EE is your client running?

**Comment by jonathan-dejong** [comment] 2015-11-19 20:06
Hmm okay.. even tho we've disabled the transactions stage? (payment stage). 
They're currently running 4.8.9

**Comment by mnelson4** [comment] 2015-11-19 20:12
Yeah, all transactions have line items, even free ones. And so that bug affected all transactions. 
And besides, if we later identify it as a different bug, and then release a bugfix, your client will need to update then anyways. So let's just update, and please also try some kind of transaction email handling for a  while to see if that fixes the problem. If neither of those do, then we have more information to find the problem

**Comment by jonathan-dejong** [comment] 2015-11-19 20:18
Okay I'll try and update. 

Regarding updates. More often than not my translations become overwritten or obsolete when updating which is a bit frustrating. Things like the line "only <number> tickets are allowed per purchase" (shown under the ticket selector) get's some kind of minor tweak and I have to redo the translations again. I get that you sometimes need to change text strings but it would really make updating smoother if I knew I could trust that most of the time my translations will hold. 
It's not really a question, more of a plead to think twice when changing strings. :)

**Comment by mnelson4** [comment] 2015-11-19 22:06
yeah I can see that's another issue to deal with everytime you upgrade. So
basically you need to re-check the translation strings EVERY time you
update Event Espresso (or really any plugin for that matter). Ya that's a
pain...

**Comment by jonathan-dejong** [comment] 2015-11-20 07:16
Yeah :) Especially since some strings can only be found on certain events or after performing a registration.

**Comment by nerrad** [comment] 2016-01-16 16:35
closing due to lack of activity, feel free to reopen if there is an update.

**Closed by nerrad** 2016-01-16 16:35 UTC
