### ISSUE TITLE
Make state and country select menus 100% width

### ISSUE THREAD

**Issue by sumobi** [eventespresso/event-espresso-core#82] opened 2015-06-05 02:07 UTC
Master branch

![screen shot 2015-06-05 at 2 04 17 pm](https://cloud.githubusercontent.com/assets/52581/7998102/ce4562de-0b8b-11e5-8b8b-92108f75240a.png)

It seems like these 2 select menus should have the same width of 100% so they look like:

![screen shot 2015-06-05 at 2 06 22 pm](https://cloud.githubusercontent.com/assets/52581/7998123/16c1a9f0-0b8c-11e5-9430-c6e443c5b02c.png)

Related: #81

**Comment by mnelson4** [comment] 2015-06-05 04:52
looks good to me imo

**Comment by nerrad** [comment] 2015-06-05 12:50
this looks like a regression.  A while ago I had done some css cleanup that made them the same width (internal: see https://events.codebasehq.com/projects/event-espresso/tickets/8302 in codebase)

**Comment by nerrad** [comment] 2015-06-05 16:23
thanks for pointing this out.  Cleanup has been merged to master.

**Closed by nerrad** 2015-06-05 16:23 UTC
Labels: ui
