### ISSUE TITLE
 PHP Deprecated:  PHP Deprecated: block_categories is deprecated since version 5.8.0! Use block_categories_all instead. is deprecated since version 5.8.0! Use block_categories_all instead.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3755] opened 2022-03-04 15:27 UTC
The title says it all really :)

`block_categories` was added in WP 5.0 and deprecated in 5.8 in favour of `block_categories_all`

https://github.com/eventespresso/event-espresso-core/blob/master/core/services/editor/BlockRegistrationManager.php#L95

(Technically not a bug, but users see the notice an assume it is, so classified it as such, feel free to change)

**Comment by hoseinrafiei** [comment] 2022-03-16 16:28
The issue is fixed in https://github.com/eventespresso/event-espresso-core/pull/3765 PR.

**Closed by hoseinrafiei** 2022-03-16 16:28 UTC
Labels: type:bug 🐞
