### ISSUE TITLE
eea-barcode-scanner

### ISSUE THREAD

**Issue by Stefanos-Stefanidis** [eventespresso/event-espresso-core#273] opened 2018-02-13 12:38 UTC
### Is this a bug report?

* [  ] no

Hi,
How can i display the attendee information when
i check with continuous scanning in with eea-barcode-scanner?
I want to display the information like the
'look up attendee'.
Thanks

**Comment by nerrad** [comment] 2018-02-13 13:13
Hi Stefanos, 

There's currently no way to do that in the add-on out of the box.  The "lookup" ui has been specifically designed around the purpose for looking up an attendee and then taking action on the results.  The continuous scan mode was designed around rabidly checkin-in or checking out attendees with the check-in/out toggle happening on scan.

Doing what you want will require custom development work.  We gladly review any pull requests that come in for actions/filters that will assist with any custom development.  This also sounds like a feature request and it could be brought up in our [support forums](https://eventespresso.com/support/forums) and potentially added to our [idea/roadmap board](https://trello.com/b/zg9DCIpe/event-espresso-public-roadmap). 

I'm just going to close this issue because there is nothing actionable here for our development team, however feel free to respond if necessary.

**Closed by nerrad** 2018-02-13 13:13 UTC

**Comment by nerrad** [comment] 2018-02-13 13:15
Issue moved to [eventespresso/eea-barcode-scanner #1](https://github.com/eventespresso/eea-barcode-scanner/issues/1) via [**ZenHub**](https://www.zenhub.com/)
