### ISSUE TITLE
Fix JavaScript error on WP > Plugins page: Jed localization error: Error: Domain `event_espresso` was not found.

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#478] opened 2018-05-25 14:49 UTC
This happens in the current release, in master branch, and in the add-type-specific-asset-methods branch.

Simply go to WP > Plugins then view the console to see this JS error:

```
Jed localization error: 
Error: Domain `event_espresso` was not found.
	memoized
index.js:74
./node_modules/@wordpress/i18n/build-module/index.js/dcnpgettext<
index.js:82
memoized
index.js:74
__
index.js:99
./assets/src/exit-modal-survey/index.js/<
index.js:38:12
./assets/src/exit-modal-survey/index.js
http://local.wordpress.test/wp-content/plugins/32-core/assets/dist/ee-wp-plugins-page.2d53dd52679d995d5e4b.dist.js:12:29
__webpack_require__
bootstrap:76
./assets/src/wp-plugins-page/index.js
http://local.wordpress.test/wp-content/plugins/32-core/assets/dist/ee-wp-plugins-page.2d53dd52679d995d5e4b.dist.js:132:76
__webpack_require__
bootstrap:76
[0]
http://local.wordpress.test/wp-content/plugins/32-core/assets/dist/ee-wp-plugins-page.2d53dd52679d995d5e4b.dist.js:23195:18
__webpack_require__
bootstrap:76
checkDeferredModules
bootstrap:43
webpackJsonpCallback
bootstrap:30
<anonymous>
http://local.wordpress.test/wp-content/plugins/32-core/assets/dist/ee-wp-plugins-page.2d53dd52679d995d5e4b.dist.js:1:2
```

**Comment by nerrad** [comment] 2018-05-25 19:46
I'm going to grab this because its something that should be fixed sooner rather than later.

**Comment by nerrad** [comment] 2018-05-25 20:36
Okay after spending some time troubleshooting I've determined that the cause for this error is when `translation-map.json` is not found by the plugin.  This is a special built file that maps javascript strings to handles that are used for on demand loading of only the strings needed for javascript on a given view.  If that map isn't present then the `wp_add_inline_script` call that sets up `eejs.i18n.setLocaleData` (which registers the `event_espresso` domain with Jed) won't get invoked and that results in the error.  There's a couple things that need fixing here:

*  Need to have the `setLocaleData` ALWAYS called regardless of whether the translation map is present or not (it can be called with an empty array of strings.
* Need to fix the build process in our build machine so that the `translation-map.json` file is always included with the build.  Right now it isn't because of the .gitignore rule that excludes it.  The .gitignore rule is there because this is a built file and we don't want built or generated files to be in our repo (as usually it will be inaccurate).

**Closed** 2018-05-30 12:06 UTC
Labels: category:assets, category:i18n, type:build-process 🔨
