### ISSUE TITLE
Count error in transactions list

### ISSUE THREAD

**Issue by eboels** [eventespresso/event-espresso-core#271] opened 2018-01-12 16:50 UTC
### Is this a bug report?

* [X ] yes
* [ ] no

### What branch did this occur in?
Master

### What version of WordPress is on the site this issue happened?
49.1

### Outline the steps to reproduce

Go to transactions list : page=espresso_transactions

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

<img src="https://photos-1.dropbox.com/t/2/AAAV3IloBT3HF17paKqQ49u8beX3euUdraYWreS4mbcavA/12/1645189/png/32x32/3/1515790800/0/2/transactions.png/EML0qwEY-MHKLCAHKAc/fUXTrBu_CrTO4D7xiXQqolrMmlG8YYf7mPdd3n-vO64?dl=0&preserve_transparency=1&size=1600x1200&size_mode=3"/>

**Comment by mnelson4** [comment] 2018-01-12 17:13
it's likely that the counts have an error in them when related data got deleted. Can you let me know what related data have you already deleted? (This will help us reproduce the issue).

**Comment by tn3rb** [comment] 2018-02-16 18:07
going to close this since the problems are due to direct db manipulation (deleting records)

**Closed by tn3rb** 2018-02-16 18:07 UTC
