### ISSUE TITLE
Question: Where to retrieve form data at checkout?

### ISSUE THREAD

**Issue by designabyss** [eventespresso/event-espresso-core#106] opened 2015-08-07 10:10 UTC
There are several hooks available via checkout such as the following:

**AHEE__SPCO__after_registration_steps**
**AHEE__SPCO_after_reg_step_form**
**'AHEE__$slug__reg_step_start**

*I want to perform an action just when the registration is complete and user is redirected to thank you page.* I have retrieved various types of data in past when dealing with event pages in order to add custom features. But the checkout process has some really complex chained classes that my mind is wobbling.

**What I want:** I need the submitted form data (at least the email) right when all the registration process is complete. Which class can I retrieve it from or is there any global object already available by the end of registration steps from which I can pick form data?

Also which of the hooks will be appropriate?

Looking forward to assistance.

**Comment by mnelson4** [comment] 2015-08-07 16:36
@tn3rb might have a better suggestion, but here's what I'd suggest: 
use the action `AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed`.
The first argument passed is the `EE_Checkout`, which has a property called `transaction` which is an `EE_Transaction` which can get you any of the registration info you're looking for (see https://github.com/eventespresso/event-espresso-core/blob/master/core/db_classes/EE_Transaction.class.php and http://developer.eventespresso.com/docs/using-ee4-model-objects/)
For example, if you want the primary registration's email, you could do:

```
add_action( 'AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed', 'my_function', 10, 2 );
function my_function( EE_Checkout $checkout ) {
    $transaction = $checkout->transaction;
    if( ! $transaction instanceof EE_Transaction ) {
        return;
    }
    $primary_reg = $transaction->primary_registration();
    if( ! $primary_reg instanceof EE_Registration ) {
       return;
    }
    $attendee = $primary_reg->attendee();
    if( ! $attendee instanceof EE_Attendee ) {
        return;
    }
    $email = $attendee->email();
    //do something with that email address

    $answers_to_custtom_questions = $registration->answers();
    foreach( $answers as $answer ) {
        $question_for_answer = $answer->question();
        //do something with each answer they have to a custom question
    }

    //etc
}
```

does that help?

**Comment by designabyss** [comment] 2015-08-12 18:49
Hello again. Thanks for the response @mnelson4.

I tried the mentioned code but when I click on 'Proceed to Final Registration', I get the following error:

**This registration step could not be completed. Please refresh the page and try again.**
This is coming via Javascript's reg_step_error

On refreshing, the page proceeds to the attendee information step where it shows the created registration.

The method I'm hooking is is creating a wp user and it is tested to be working on its own.

```php
function espresso_create_wp_user(EE_Checkout $checkout) {

    $transaction = $checkout->transaction;
    if( ! $transaction instanceof EE_Transaction ) {
        return;
    }
    $primary_reg = $transaction->primary_registration();
    if( ! $primary_reg instanceof EE_Registration ) {
       return;
    }
    $attendee = $primary_reg->attendee();
    if( ! $attendee instanceof EE_Attendee ) {
        return;
    }
    $email = $attendee->email();

    if( username_exists( $email ) == NULL ) {  
        
        // Generate the password and create the user
        $password = wp_generate_password( $length=12, $include_standard_special_chars=false );
        $user_id = wp_create_user( $email, $password, $email );

        // Set the role
        $user = new WP_User( $user_id );
        $user->set_role( 'attendee' );
    
        // Email the users
        wp_mail( $email, 'Welcome to PartyCloud', 'Your Username: ' .$email. ' Your Password: ' . $password );
    
    }
}
```

**Comment by mnelson4** [comment] 2015-08-12 20:44
It would help if you could attach the ajax response body when there is an error (eg use a web inspector to see what the AJAX response looks like) it might have an error in it that will tell us

**Comment by designabyss** [comment] 2015-08-13 00:50
![xhr](https://cloud.githubusercontent.com/assets/8544814/9240337/50fefb2c-417e-11e5-9259-dda34473f658.PNG)

```
XHR Loaded (admin-ajax.php - 200 OK - 3.2250459999995655s - 572B)
http://127.0.0.1/partycloud/wp-admin/admin-ajax.php?ee_reg_qstn%5B39%5D%5Bf…nformation&EESID=0b5c4c70db1675f76c74d56e119f03a3&revisit=&e_reg_url_link=
Time over 1000ms
Object {startedDateTime: "2015-08-13T00:45:24.217Z", time: 3225.0459999995655, request: Object, response: Object, cache: Object…}
XHR Loaded (admin-ajax.php - 200 OK - 6.540345999994315s - 6.445KB)
http://127.0.0.1/partycloud/wp-admin/admin-ajax.php?action=display_spco_reg…ont_ajax=1&EESID=0b5c4c70db1675f76c74d56e119f03a3&revisit=&e_reg_url_link=
Time over 1000ms
Object {startedDateTime: "2015-08-13T00:45:27.453Z", time: 6540.345999994315, request: Object, response: Object, cache: Object…}cache: Objectconnection: "5536"pageref: "page_2"request: ObjectbodySize: 172cookies: Array[48]headers: Array[12]headersSize: 2566httpVersion: "HTTP/1.1"method: "POST"postData: ObjectqueryString: Array[0]url: "http://127.0.0.1/partycloud/wp-admin/admin-ajax.php"__proto__: Objectresponse: Object_transferSize: 6445bodySize: 5922content: Objectcompression: 0mimeType: "text/html"size: 5922__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()cookies: Array[0]length: 0__proto__: Array[0]headers: Array[15]0: Objectname: "Pragma"value: "no-cache"__proto__: Object1: Objectname: "Date"value: "Thu, 13 Aug 2015 00:45:27 GMT"__proto__: Object2: Objectname: "X-Content-Type-Options"value: "nosniff"__proto__: Object3: Objectname: "Server"value: "Apache/2.4.9 (Win64) PHP/5.5.12"__proto__: Object4: Objectname: "X-Powered-By"value: "PHP/5.5.12"__proto__: Object5: Objectname: "X-Frame-Options"value: "SAMEORIGIN"__proto__: Object6: Object7: Objectname: "Access-Control-Allow-Origin"value: "http://127.0.0.1"__proto__: Object8: Objectname: "Cache-Control"value: "no-cache, must-revalidate, max-age=0"__proto__: Object9: Objectname: "Access-Control-Allow-Credentials"value: "true"__proto__: Object10: Objectname: "Connection"value: "Keep-Alive"__proto__: Object11: Objectname: "X-Robots-Tag"value: "noindex"__proto__: Object12: Object13: Object14: Objectlength: 15__proto__: Array[0]headersSize: 523httpVersion: "HTTP/1.1"redirectURL: ""status: 200statusText: "OK"__proto__: ObjectstartedDateTime: "2015-08-13T00:45:27.453Z"time: 6540.345999994315timings: Objectblocked: 0.798000000941102connect: -1dns: -1receive: 0.6240000002453598send: 0.572999997530128ssl: -1wait: 6538.350999995599__proto__: Object__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()

```

That helps?

**Comment by mnelson4** [comment] 2015-08-13 04:12
meuh not too much. I think it will be easier to just copy-and-paste that
code into my functions.php, along with an `add_filter(...)` call, when I
get a chance (atm we're trying to get 4.8 out the door)

**Comment by tn3rb** [comment] 2015-08-13 16:32
@designabyss 
You're going to need to dig into those responses to see more info. Click on the little triangle just before where it says "Object" to see more info. Look for any errors that might be disrupting things. Other thing you can do is check your php error logs to see if there's anything in there.

**Comment by mnelson4** [comment] 2015-08-24 19:05
hey @designabyss I just tried adding this chunk of code to my functions.php file
```
add_action( 'AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed', 'espresso_create_wp_user', 10, 2 );
function espresso_create_wp_user(EE_Checkout $checkout) {

    $transaction = $checkout->transaction;
    if( ! $transaction instanceof EE_Transaction ) {
		throw new EE_Error( 'no transaction');
        return;
    }
    $primary_reg = $transaction->primary_registration();
    if( ! $primary_reg instanceof EE_Registration ) {
		throw new EE_Error( 'no primary reg');
       return;
    }
    $attendee = $primary_reg->attendee();
    if( ! $attendee instanceof EE_Attendee ) {
		throw new EE_Error( 'no attendee');
        return;
    }
    $email = $attendee->email();

    if( username_exists( $email ) == NULL ) {

        // Generate the password and create the user
        $password = wp_generate_password( $length=12, $include_standard_special_chars=false );
        $user_id = wp_create_user( $email, $password, $email );

        // Set the role
        $user = new WP_User( $user_id );
        $user->set_role( 'attendee' );

        // Email the users
        wp_mail( $email, 'Welcome to PartyCloud', 'Your Username: ' .$email. ' Your Password: ' . $password );

    }
}add_action( 'AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed', 'espresso_create_wp_user', 10, 2 );
function espresso_create_wp_user(EE_Checkout $checkout) {

    $transaction = $checkout->transaction;
    if( ! $transaction instanceof EE_Transaction ) {
		throw new EE_Error( 'no transaction');
        return;
    }
    $primary_reg = $transaction->primary_registration();
    if( ! $primary_reg instanceof EE_Registration ) {
		throw new EE_Error( 'no primary reg');
       return;
    }
    $attendee = $primary_reg->attendee();
    if( ! $attendee instanceof EE_Attendee ) {
		throw new EE_Error( 'no attendee');
        return;
    }
    $email = $attendee->email();

    if( username_exists( $email ) == NULL ) {

        // Generate the password and create the user
        $password = wp_generate_password( $length=12, $include_standard_special_chars=false );
        $user_id = wp_create_user( $email, $password, $email );

        // Set the role
        $user = new WP_User( $user_id );
        $user->set_role( 'attendee' );

        // Email the users
        wp_mail( $email, 'Welcome to PartyCloud', 'Your Username: ' .$email. ' Your Password: ' . $password );

    }
}
```
(almost exactly what you had)
and it's creating users and emailing them fine. I suspect the error you were getting was temporary (probably from branch switching, or leaving a registration alone for too long, or some other unique circumstances which are hard to reproduce) and would have gone away had you tried a brand new registration.

But using `$checkout->primary_attendee_obj` is a-ok too.
Closing this ticket seeing how you got it working. Feel free to reopen or comment

**Closed by mnelson4** 2015-08-24 19:05 UTC
Labels: question
