### ISSUE TITLE
The "Payment Received" message not queued

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#3838] opened 2022-05-16 13:48 UTC
While adding the "Payment Received" message into the queue it is sending the message directly.

https://user-images.githubusercontent.com/99984614/168607373-9ad389be-be72-40de-b4dc-116ea685dbf3.mp4

**Comment by tn3rb** [comment] 2022-05-16 20:39
Not sure what you are expecting here...

I think there is likely a couple of things off with your expectations. 

1.  Setting the "Generate and send all messages" option to "On a separate request" does not mean that messages are queued up and sit there for any amount of time. They will most likely be sent on the very next request that is detected. This is done because processing the registration checkout form can sometimes be extremely intensive if there are a LOT of registrants and/or registration form questions. Trying to ALSO process a bunch of emails on top of that can sometimes be too much for some servers to handle (especially cheaper shared hosting), so that message setting simply defers the message generation and sending until the next request to help spread out all of that processing. Messages _should_ still appear to send almost immediately.

2.  Most, if not all admin requests that execute some kind of change, either submitting a form or toggling some setting, will first execute a POST (or GET) request followed by a redirect / GET request  to the screen where the first request originated from. So when you clicked on that "Queue for Resending" action, the messages get queued during your initial request, and likely get sent on the second request which redirected you back to the messages list table. Therefore it appears that the messages were not queued up at all. 

Why does the UI show separate list table views for queued messages? Because the cron interval for triggering messages _can_ be modified by users via a filter. So for example, someone _could_ set their messages to go out once per hour, or once per day, or whatever. The "Queued For Sending" or "Queued For Resending" views will therefore show messages that are waiting to be sent. If you have not modified your messages cron schedule via a filter, then your queued messages are most certainly being sent on the very next request.

If this sounds confusing... well it kinda is and could possibly have been done better, but that's difficult given the wide range of server conditions and user configurations we have to deal with.

**Comment by Pebblo** [comment] 2022-05-19 11:04
So, the short answer here is that 'Payment' related messages are considered to be a higher priority than registration messages and so payment related emails will skip the queue and be processed immediately.

To explain a little, the message queue system works on WP-Cron and the time it takes for a message to 'work' through the system could be up to 10mins .... again that is by default and the value could have been changed by end-users, meaning we could be looking at say an hour or more in some cases.

For a registration message which is triggered after the user arrived at the thank you page, which by default shows details of the registration itself, it means that for most people it's not as critical that you receive a message stating 'Heyyyy thanks for registering, here are the details you just registered with' straight away. In short meaning it's okay for 'Registration' messages to be a little delayed as they work through the system to send.

However.... that kinda changes for payment related emails. Personally, I want to know straight away if my payment was Approved/Denied and an email stating such does exactly that (although so does the checkout process and the thank you page, but that's another story!) even if my registration data takes a little.

So the message system basically skips the message queue for payment emails and sends them immediately and leaves the batch processing to work on the registration related messages because they aren't as critical (at least that's the idea).

So the behaviour in this ticket is actually expected behaviour here and I would expect those payment related messages to trigger and send immediately.

@Saam01 may I ask, did you run into an issue with the happening or was it just something you noticed?

The message system is indeed confusing with multiple working parts that all align to make the world spin, Brent is guessing what your expectations for that feature are above and could have been way off the mark (I don't think he is) as after all he's just guessing.

Whilst there isn't anything 'wrong' with your opening ticket, it helps to add some context when creating a ticket so we know why you've created it, what you expected and why, if it was reported as an issue by a customer or something you found whilst testing etc. Basically a brief overview of that the issue is, why you see it as an issue and how you found it all helps give context to the ticket itself and reduces the amount of guesswork the next person needs to do to figure it out.

**Comment by Saam01** [comment] 2022-05-19 12:01
@tn3rb @Pebblo Thanks for explaining.

I found the above while testing the checklist for queue messages. 

And I think you are right the payment email don't need to be in queue.

**Comment by tn3rb** [comment] 2022-05-23 19:32
going to close this then

**Closed as completed by tn3rb** 2022-05-23 19:32 UTC
