### ISSUE TITLE
Reserved ticket counts after a cancelled registration

### ISSUE THREAD

**Issue by zouidi** [eventespresso/event-espresso-core#269] opened 2017-12-31 08:58 UTC
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ x ] yes
* [ ] no

### What branch did this occur in?
event-espresso-core

### What version of WordPress is on the site this issue happened?
WordPress  '4.8.2';

### If you were directed to create an issue here by the EE support team, what is the link to your original EE support forum thread?
https://eventespresso.com/topic/cancelled-registration-and-reserved-ticket-counts/

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
https://ibb.co/jR30sG
https://ibb.co/nQ4jKw

**Comment by mnelson4** [comment] 2018-01-01 17:49
hi @zouidi, like Josj said on the support forum, we have created an internal ticket and will be addressed as soon as we're able. I don't think we need another ticket in github

**Comment by zouidi** [comment] 2018-01-02 08:48
Problem solved by changing the default value of $quantity to 0 in:
**EED_Ticket_Sales_Monitor.module.php** file, function _release_reserved_ticket(EE_Ticket $ticket, **$quantity = 0**).

**Comment by joshfeck** [comment] 2018-01-02 15:17
Internal ticket #11268

**Comment by tn3rb** [comment] 2018-01-03 00:03
@zouidi 

Assuming your fix doesn't cause other issues and is  accepted, are you interested in creating a pull request for your fix so that you can get credit for it?

**Comment by tn3rb** [comment] 2018-02-16 17:43
fiz has been pushed to branch: 
https://github.com/eventespresso/event-espresso-core/tree/BUG/11268/session-ticket-release
plz feel free to test this on a non-production site (ie: a test site)

**Comment by tn3rb** [comment] 2018-04-19 15:38
for testing plz see: https://events.codebasehq.com/projects/event-espresso/tickets/11268

**Comment by sethshoultes** [comment] 2018-04-23 19:56
### testing

 * we need two browser windows that are using separate sessions, so either use two different browsers (like Chrome + FF) or use a private window for one of the sessions
 * in browser A find an event with an available ticket and select 3, proceed to checkout, but stop on the first step
 * in browser B go to the **same event** as above and select 5 of the **same ticket**, proceed to checkout, and also stop on the first step
 * in another browser tab or window (doesn't matter if it's sharing a session with A or B) log into the admin
 * go to the event editor for the same event as above, find the ticket that you selected above, and look at its "**Rsrvd**" quantity
 * [ ] confirm that the  "**Rsrvd**" quantity is 8
 * now switch to browser A (the one with 3 tickets) and go to `your-domain.com/registration-cancelled/` to cancel the registrations
 * switch back to your browser tab that is open to the event editor and refresh the page
 * [ ] confirm that the  "**Rsrvd**" quantity is now 5
 * feel free to experiment with selecting tickets then cancelling and watching the  "**Rsrvd**" quantity in the admin, but be aware of your session expiration time and remember that tickets are released when you complete the reg process (get to the thank you page)
 * compare any potential issues found against master branch to confirm that the problem is with the work done in this branch

**Comment by joshfeck** [comment] 2018-04-26 14:40
@tn3rb can you resolve the merge conflicts from merging master into this branch?

**Comment by tn3rb** [comment] 2018-04-30 20:45
ready to go

**Comment by joshfeck** [comment] 2018-05-07 22:02
This is ready for merging.

**Comment by tn3rb** [comment] 2018-05-07 22:36
merged to master and all remotes deleted

**Closed by tn3rb** 2018-05-07 22:36 UTC
Labels: category:has-codebase-ticket, status:needs-testing, type:bug
