### ISSUE TITLE
Allow trashed events to be deleted and at the same time prevent them from orphaning other data records GDPR

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#349] opened 2018-04-25 03:40 UTC
See original Codebase ticket:
https://events.codebasehq.com/projects/event-espresso/tickets/9009

This has come up in the forums and I think there's some room for improvement when it comes to making things easier for event managers.

Steps to reproduce: 
1) Set up an event and assign some people CPTs to the event, save the event.
2) Trash the event
3) Go the trashed events view in the wp admin list table
4) check the box next to the event
5) select the Delete Permanently action and click Apply

Result is you'll see some errors that say you can't delete the event. So now you have to go and restore the event from the trash, then you have to edit the event, and remove all of the relationships to things like People CPts. Then trash, then you can permanently delete.

Can we change the above so the relationships automatically get removed so all they'll have to do is trash then delete the event?

**Comment by sethshoultes** [comment] 2018-04-25 16:24
Oops. Didn't mean to do that. I updated the category to GDPR.

**Comment by mnelson4** [comment] 2018-06-26 14:42
thanks Stale bot, but I'm pretty sure we still intend to work on this

**Comment by joshfeck** [comment] 2019-01-10 15:01
see also:
https://events.codebasehq.com/projects/event-espresso/tickets/7290

**Comment by joshfeck** [comment] 2019-10-18 17:26
Would this also allow for deleting events that have registrations?

**Comment by mnelson4** [comment] 2019-10-18 17:28
I don't think it's been specified. What would customers probably want to happen when deleting an event with registrations? orphan them? block deletion of the event until registrations are deleted? automatically delete all the registrations too?

**Comment by joshfeck** [comment] 2019-10-18 17:59
The current behavior is it blocks deletion of the event until registrations are deleted.

Would it be OK to instead allow the event to be deleted and orphan the registrations?

**Comment by mnelson4** [comment] 2019-10-21 20:41
> Would it be OK to instead allow the event to be deleted and orphan the registrations?

It would certainly test how defensive our code- the code should generally just say "oups, can't find the event for this registration" and then keep working. But there may be the odd fatal error that would happen because we got careless.

Although I've reviewed this ticket some more: I think this work would only help with GDPR and user privacy etc if it actually facilitated deleting registrations/contacts. Just deleting the event and orphaning the registrations doesn't help with GDPR because the personal information (on the registration and contact) is still in the system.

I'm actually not sure what use-case facilitating just deleting the event (and orphaning its related data) would benefit.

So I would think this is really only useful if it will also delete the personal information contained on registrations and contacts etc.

**Comment by joshfeck** [comment] 2019-10-24 19:51
Since there's likely a lot of data that may need to be deleted, would this be something we'd use the Batch system to break things up into smaller requests?

On a site without MER, it'd probably be fairly straightforward to delete an event and its related data:

### Delete:

event post in wp_posts
any post meta
datetimes
tickets
prices
registrations
transactions
line items
payments
relationship records to wait lists, people CPTs, Venues

Contacts related to the registrations would remain because you can have contacts without a registration, and there may be other registrations for other events attached to any given Contact.

Where things could get sticky is on sites where MER is activated. Maybe that would require doing a check on the transactions and if the transaction has line items from other events, then the transaction needs to persist.

**Comment by mnelson4** [comment] 2019-10-25 16:32
> Since there's likely a lot of data that may need to be deleted, would this be something we'd use the Batch system to break things up into smaller requests?

Yes I think that would be appropriate (especially for those events with hundreds of attendees).

> Do not delete... Contacts

I suspect users will be divided on this: some will want the contacts gone too (eg if the contacts are only for one event and the event manager is trying to adhere to GDPR's "Privacy by Design" and delete old data), while others will want to keep them. It's a similar situation with venues (and transactions with MER, like you mentioned), because those can be for different events.

I think it would be best if we asked users if they want to delete contacts, transactions, venues, etc (provided they're not in use by other events); and it would be nice to have a confirmation page (where we display what data, including related data, will get deleted)

**Comment by joshfeck** [comment] 2019-10-25 16:53
I don't think venues should be deleted when an event is deleted. The relationship between an event and venue would be deleted, but allowing a venue to be deleted when an event is deleted would probably lead to accidental deletion of venues. A user can delete venues already via the Venues list table.

**Comment by mnelson4** [comment] 2019-10-31 18:19
# UI Considerations
So when deleting an event, we could add a "confirmation" page, that could confirm everything that will get deleted with it.
For the first version, I'd like to not bother with any options, and just delete the essential stuff. [Following Josh's list](https://github.com/eventespresso/event-espresso-core/issues/349#issuecomment-546075700) IMO that's:

* event meta
* datetimes
* tickets
* prices for those tickets (not general price modifiers or default prices)
* message templates
* registrations
* registration answers
* relations to wait lists, people, venues

Contacts and transactions (and the transaction's associated payments and line items) can exist OK without associated events. So for the initial version of this, I'm inclined to leave them.

# Code Considerations

WIP...

**Comment by joshfeck** [comment] 2019-11-04 18:59
> Contacts and transactions (and the transaction's associated payments and line items) can exist OK without associated events.

This is true, but as it stands now, a transaction must have at least one registration. Otherwise there's a fatal error:
```Fatal error: Uncaught Error: Call to a member function reg_code() on bool in /Applications/MAMP/htdocs/ee4/wp-content/plugins/32-core/admin_pages/transactions/Transactions_Admin_Page.core.php:1046
```
We could make the above more defensive to avoid fatal errors. Not deleting transactions does solve the problem of what to do about MER and how it allows a transaction to have registrations from several events. So no issue if all registrations from one event are deleted, and some transactions have registrations from that event and registrations from other events.

The downside would be there's currently no UI to delete transactions, which between those and line items it can also add quite a bit of data onto the database. 


> do we want to have a confirmation page?

Either a confirmation page or an alert that allows the user to get out if they got there by mistake.

**Comment by mnelson4** [comment] 2019-11-08 18:45
> The downside would be there's currently no UI to delete transactions, which between those and line items it can also add quite a bit of data onto the database.

I'd be inclined to get this working without deleting transactions (assuming it doesn't take a crazy amount of effort to avoid that fatal error you mentioned and others like it), and then add the ability to delete transactions on a separate ticket.

> Either a confirmation page or an alert that allows the user to get out if they got there by mistake.

I'm inclined to do the confirmation page because it's also an opportunity to point out all the related data that will get deleted...

Any further thoughts on that? If not, we should probably get feedback from Brent next.

**Comment by joshfeck** [comment] 2019-11-08 20:32
It probably wouldn't take much to make the code a bit more defensive.

**Comment by mnelson4** [comment] 2019-11-11 18:11
KK, I'd like to make a p2 with a proposal, especially looking for feedback from Brent and anyone who wants to chime in.

**Comment by mnelson4** [comment] 2019-11-11 19:05
[Here's the p2](http://p2.eventespresso.com/2019/11/11/cascading-deletions-to-ease-deleting-events-and-associated-registrations/), based on [my earlier post on this ticket](https://github.com/eventespresso/event-espresso-core/issues/349#issuecomment-548505642), but I removed some of the questions because I get the impression we're inclined to have the confirmation page, and will leave transactions alone initially. (If that' incorrect chime in here or there.)

While I'm open to feedback from everyone, I think only Brent's additional blessing is needed to move forward.

**Comment by mnelson4** [comment] 2019-11-22 22:18
Ok so the main feedback from the p2 so far is:

* [ ] make sure users have a database backup before deleting
* [ ] have users confirm the event they're wanting to delete (like how GitHub gets you to type in the repo's name). The details of this are being discussed
* [ ] business logic would probably fit in  `/core/services/admin` or even `/core/services/orm folder`
* [ ] if more meta-info is required to make this work, it may be best to store in model-specific config files, rather than directly on the models
* [ ] using the command bus seems appropriate
* [ ] log when events were deleted (although having a UI to show them isn't yet essential)

**Comment by mnelson4** [comment] 2019-11-22 22:30
# The plan:

* [ ] write a business class for traversing a model's dependent relations (all in one go) and test
* [ ] make it divisible/batcheable and test
* [ ] generate the preview page via a batch job 
* * [ ] count the records- tricky because what we're doing is discovering
* * [ ] keep track of where we left off
* * [ ] store the built tree (even when it has thousands of entries)
* [ ] display the preview page (in a way that can handle thousands of entries)
* [ ] reorganize the tree of data into flat lists of items (eg all the registrations, all the answers)
* [ ] execute the deletion
* [ ] record the deletion
* [ ] make the deletions use the command bus

**Comment by mnelson4** [comment] 2019-11-26 18:37
I've created sub-tickets for the different parts of this project, so closing this one

**Closed by mnelson4** 2019-11-26 18:37 UTC
Labels: category:GDPR, status:feedback-needed, type:enhancement 🎉
