### ISSUE TITLE
More gracefully degrade the PDF Icon on the View Full Order Confirmation Receipt button in the Checkout

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#613] opened 2018-07-30 20:54 UTC
Josh said we can probably degrade this more gracefully

Reported here: https://secure.helpscout.net/conversation/630966403/552862?folderId=284418

**Comment by joshfeck** [comment] 2018-08-17 20:27
I looked into this and I had no trouble loading the PDF Icon going back to IE9. The user that reported this may have had a browser setting set to not allow loading font icons.

**Comment by joshfeck** [comment] 2019-01-28 20:34
I wonder if this would be fixed by removing the sans-serif fallback?

<img width="443" alt="screen shot 2019-01-28 at 3 32 06 pm" src="https://user-images.githubusercontent.com/891156/51864561-1af29600-2312-11e9-9108-87855e551a25.png">

**Comment by joshfeck** [comment] 2019-01-28 22:08
I've looked into this further and I don't see a way to reliably check if the browser has loaded the custom ee custom icon fonts before trying to use them. The cause of the icon not showing would have been something in their security settings. 

We could **remove** the custom icon there, would it be better to not show anything there at all other than the text?

**Comment by sethshoultes** [comment] 2019-01-28 23:04
If they are having issues with that icon, then it's likely they are having issues with other icons as well. I don't like the idea of removing the icon just because this one person's security settings are turned up too high, etc. However, I think we could just hide the icon on that site with a little CSS if they are reluctant to change their security settings.

**Comment by joshfeck** [comment] 2019-01-29 14:51
OK we'll close this then.

**Closed by joshfeck** 2019-01-29 14:51 UTC
Labels: status:feedback-needed
