### ISSUE TITLE
Closing PHP version notice also closes the timezone selector

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#863] opened 2018-12-26 20:05 UTC
Originally reported in [11238](https://events.codebasehq.com/projects/event-espresso/tickets/11238) and later in [11350](https://events.codebasehq.com/projects/event-espresso/tickets/11350)

> When closing out the PHP notice in the event editor (on a new site), it also closes out the timezone selector:
> https://www.screencast.com/t/FXrtQAw1k

One idea brought forth in 11350 was to put the timezone setting UI in a modal. The important thing is the timezone setting box needs to be set without reloading the page and needs to stay open if another notice is dismissed.

**Comment by joshfeck** [comment] 2019-11-12 02:25
This will no longer be an issue after the entire event editor UI is converted.

**Comment by tn3rb** [comment] 2022-01-31 19:31
@hoseinrafiei 
can you plz look into this and find out what DOM element id and/or class(es) are causing this issue?

The PHP notice can be found in `EventEspresso\core\services\request\middleware\RecommendedVersions` but not sure off the top of my head where the timezone selector is, so you'll have to search for that

**Comment by hoseinrafiei** [comment] 2022-02-01 12:23
@tn3rb 

I cannot reproduce this issue anymore.
Please check this video: https://monosnap.com/file/BRzh0Xeedgjh37RasqH6PA3d5nqWKQ

I enabled all of those 3 notices temporarily and as you can see in the video, dismissing the PHP upgrade notice doesn't have any impact on the timezone selector and it remains open.

Please advise.

**Comment by tn3rb** [comment] 2022-02-04 17:57
there's a critical piece of info in the issue description that may have been easy to miss:

> When closing out the PHP notice in the event editor (on a new site)

were you testing on a brand new site? No worries if you missed that, but it is a critical point that needs to eb taken into consideration.

This kind of issue can be a huge PITA (pain in the 4$$) because it requires a huge amount of setup to test it.
What system you are you using for local site development can make a big difference:

- Local by Flywheel - super easy and fast to spin up new sites
- Vagrant - lots of manual config required (unless there is something new to help with that)
- WSL- lots of manual config required (unless you use a shell script)
- ???

I use WSL, but would be tempted to install Local just for a situation like this, because it's so super fast and easy to spin up a new site.

ANYWAYS, all of that said... if you **DID** test that on a brand new site, then the issue must have been resolved elsewhere and we can simply close this.

**Comment by hoseinrafiei** [comment] 2022-02-08 14:07
@tn3rb

For the local websites, I use Laravel Valet to create websites and WP Reset plugin to reset websites. Last week I tested the issue on my dev and a fresh website. Today, I tested with a fresh website created by Local by Flywheel and everything works fine and I wasn't able to recreate the issue.

Therefore, based on your advise I'm closing this issue.

**Closed by hoseinrafiei** 2022-02-08 14:07 UTC
Labels: type:bug 🐞, category:admin-page-ui-&-ux, type:user-proofing 🛡
