### ISSUE TITLE
Implement a way to capture more information when wp_mail fails

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#382] opened 2018-05-04 13:47 UTC
## Issue Overview

Currently when the messages system passes off things to `wp_mail` it only receives a boolean response on whether the message was successfully sent or not.  This means by default, there's no useful information to pass on the the end user for why an email failed to send.  For the longest time, I've thought there IS no way to access useful information without clobbering the native `wp_mail` function.  However, it turns out, we may have an option.  I took a closer look at `wp_mail` today and I see this:

```
/** This filter is documented in wp-includes/pluggable.php */
		do_action( 'wp_mail_failed', new WP_Error( 'wp_mail_failed', $e->getMessage(), $mail_error_data ) );
```

It's possible we can hook into that right before calling `wp_mail` in `EE_Email_Messenger` and then capture any further error messages and return them back through to the `EE_Messages_Queue`.    This would hopefully give us more info to pass on through to the end user with the error message displayed in the messages list table.

A caveat is that since `wp_mail` is a pluggable function, there's no guarantee that any plugins overriding `wp_mail` would expose the same action.  However, I still think its worth implementing because at least for some cases we'll probably get more information exposed.

**Comment by joshfeck** [comment] 2019-01-29 21:37
This is basically a duplicate of https://events.codebasehq.com/projects/event-espresso/tickets/8862, and we discussed this in Slack and we're going to do a snippet and add it to the library instead of adding something to core that's mostly only going to be used for debugging.

**Closed by joshfeck** 2019-01-29 21:37 UTC
Labels: category:messaging-&-messengers, type:enhancement 🎉
