### ISSUE TITLE
str.replace is not a function

### ISSUE THREAD

**Issue by PunchRockgroin** [eventespresso/event-espresso-core#155] opened 2016-03-28 18:47 UTC
Greetings!

Running into an issue across all browsers regarding the new is_email function. Looks like the "Loop through each sub" test is somehow passing a function instead of a string to the test, causing the test to fail on any valid email.

I've added console.logs in the str_trim function to illustrate:

![2016-03-28 12_41_50-clipboard](https://cloud.githubusercontent.com/assets/1855836/14086545/d873601c-f4e2-11e5-8dd7-b47df49ec968.jpg)

As well, the error message when the form is submitted with the so-called invalid email returns "First name is required".

For now, my fix is to return true before the sub loop.

**Comment by nerrad** [comment] 2016-03-28 19:14
I just took a quick gander at the code.  The only way I could see this maybe happening is if you have javascript loading before this particular js that defines a `test` function.  That in turn may be what is triggering this.  Are you able to confirm whether that is the case in your environment?

We are unable to reproduce on our test sites while trying to validate `test@test.com`

**Comment by nerrad** [comment] 2016-03-28 22:24
actually my theory is incorrect as well... from your console.log dump it looks like it's already looped through `test` and `com`

**Comment by nerrad** [comment] 2016-03-28 22:27
I think it's likely this has something do with this method being in the scope of the `jQuery.ready` callback and the usage of `$`

**Comment by tn3rb** [comment] 2016-04-04 22:25
@PunchRockgroin 

I've pushed a potential fix for this issue for you. If you have a testing site, can you please checkout the https://github.com/eventespresso/event-espresso-core/tree/BUG-9564-forms-js-str.replace branch and test if this fixes the reported issue for you ?

Please always back up your database before performing any kinds of activations, upgrades, etc.

thank you

**Comment by PunchRockgroin** [comment] 2016-04-04 22:37
@tn3rb 

Tested and working!

Thanks!

**Closed** 2016-07-25 13:49 UTC
Labels: bug
