### ISSUE TITLE
Payment Gateway duplicate calls

### ISSUE THREAD

**Issue by jonathanjulian** [eventespresso/event-espresso-core#210] opened 2017-02-22 20:17 UTC
Hi

I have built and payment gateway plugin for payment express using your skelton payment gateway plugin.

The problem i’m having is that once payment has been made on payment expresses hosted payment page it triggers a success url response every few seconds while still on their page, until they redirect back to the EE site, this is to make sure the response gets through. so this means the handle_payment_update() function is running multiple times which then triggers multiple copies of the emails to be sent.

I am trying to add an if statement around the handle_payment_update() function to make sure the current payment status different to the payment status returned from the payment gateway

this is the if statement i am trying but with no success
`if( $payment->status() != $update_info[ 'status' ] ){`

the full function

```php
public function handle_payment_update($update_info, $transaction) {
    if( ! isset( $update_info[ 'uts' ] ) ){
        return NULL;
    }
    $payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr($update_info[ 'uts' ] );
    if($payment instanceof EEI_Payment && isset( $update_info[ 'status' ]) && $payment->status() != $update_info[ 'status' ] ){
        if( $update_info[ 'status' ] == $this->_pay_model->approved_status() ){
            $payment->set_status( $this->_pay_model->approved_status() );
            $payment->set_gateway_response( __( 'Payment Approved', 'event_espresso' ));
        }elseif( $update_info[ 'status' ] == $this->_pay_model->pending_status() ){
            $payment->set_status( $this->_pay_model->pending_status() );
            $payment->set_gateway_response( __( 'Payment Pending', 'event_espresso' ));
        }elseif( $update_info[ 'status' ] == $this->_pay_model->declined_status() ){
            $payment->set_status( $this->_pay_model->declined_status() );
            $payment->set_gateway_response( __( 'Payment Declined', 'event_espresso' ) );
        }else{
            $payment->set_status( $this->_pay_model->failed_status() );
            $payment->set_gateway_response( __( 'Payment Failed', 'event_espresso' ) );
        }
    }
    return $payment;
}
```

any help to only trigger this function on change of status would be great thank you.

Jonathan

**Comment by tn3rb** [comment] 2017-02-22 20:21
you likely just need to save the payment after updating its status using:

```php
$payment->save();
```

**Comment by jonathanjulian** [comment] 2017-02-22 20:31
The status is updating the transaction even if it is already complete. so when the payment processor  send me multiple payment complete urls triggers emails for each time, but i only want the payments updated if the payment status if different to what it already is.

**Comment by mnelson4** [comment] 2017-02-22 20:45
what is the value of `$update_info[ 'status' ]` on a successful payment? I bet it's something like 'success'.

Well, the value of `$payment->status()` can be one of the following: `PAP` (for approved), `PFL` (for failed), `PDC` (for declined) and there might be some more listed on `EEM_Payment`.

So your conditional should be something like this insead

```
switch($update_info['status']){
  case 'success':
    $new_payment_status = $this->_pay_model->approved_status();
    break;
  case 'failure':
    $new_payment_status = $this->_pay_model->failed_status();
    break;
  //....other cases
}
if( $new_payment_status !== $payment->status()){
    //...then it must not be a duplicate, so process it
)
```
Note: it sounds like you actually shouldn't need to be saving the payment at all, that's done by other code later on in the request

**Comment by tn3rb** [comment] 2017-02-22 20:45
what do some of the values for ` $update_info[ 'status' ] ` look like ? I'm assuming that that is a value being sent from the gateway itself and doubt that it would exactly match what we use for payment statuses in EE.
What is the payment status after the above function runs?
You can determine the payment status by looking at the Transaction details in the admin, and checking the coloured stripe on the far left of the payment record in the Payment Details table. 
Do you see green stripes (approved payments) or Orange stripes (failed) ?

**Comment by jonathanjulian** [comment] 2017-02-22 20:51
the uts value are PAP, PPN or PFL like Event espresso.

so you are saying $payment->status() should return PAP on an already approved payment.

maybe it is not the payments gateways calls that are triggering my email issue.
it is only the processing payment emails which are being sent over and over again (like 7 times every 2 minutes) not the confirm booking email.

**Comment by tn3rb** [comment] 2017-02-22 20:54
what do the values for $update_info[ 'status' ] look like ?

**Comment by tn3rb** [comment] 2017-02-22 20:57
and ` $this->_pay_model->get_payment_by_txn_id_chq_nmbr($update_info[ 'uts' ] ); ` 
should use a unique identifier for finding a specific payment (ie: some kind of ID).
if you are using values like 'PAP' for $update_info[ 'uts' ], then that's not going to work very well, as you will quickly end up with multiple payments using that same string

**Comment by jonathanjulian** [comment] 2017-02-22 20:59
sorry i meant the status is equal to PAP and yes the uts  is the ID

**Comment by tn3rb** [comment] 2017-02-22 21:04
so the gateway you are connecting to just happens to return the **EXACT** same status codes that EE uses?!?!?

ie: when the gateway wants to indicate that a payment is approved, they return 'PAP' as the status string?
And if the payment is declined, they return 'PDC' ???

I highly recommend that you triple check that that is true. 
The chances of a gateway using the exact same status code as EE seems somewhat unlikely.

Once that has been confirmed, then I would like to know what you see in the **Payment Details** table when you go to the EE Admin > Transactions list table, and click on one of these transactions to see its details.

**Comment by jonathanjulian** [comment] 2017-02-22 21:05
ok i have updated the code to

```
$payment = $this->_pay_model->get_payment_by_txn_id_chq_nmbr($update_info[ 'uts' ] );
	 if($payment instanceof EEI_Payment &&  isset( $update_info[ 'status' ])  ){
	 switch($update_info['status']){
	  case 'PAP':
	    $new_payment_status = $this->_pay_model->approved_status();
			$new_payment_response = 'Payment Approved';
	    break;
		case 'PPN':
	    $new_payment_status = $this->_pay_model->pending_status();
			$new_payment_response = 'Payment Pending';
	    break;
	  case 'PFL':
	    $new_payment_status = $this->_pay_model->failed_status();
			$new_payment_response = 'Payment Failed';
	    break;
		}
		if( $new_payment_status !== $payment->status()){
    //...then it must not be a duplicate, so process it
			$payment->set_status( $new_payment_status );
			$payment->set_gateway_response( __( $new_payment_response , 'event_espresso' ));
		 }else{
			 $payment->set_status( $this->_pay_model->failed_status() );
			 $payment->set_gateway_response( __( 'Payment Failed', 'event_espresso' ) );
		 }
	 }
	 return $payment;
```

and it look like the functions works but doesn't solve my email issue. I am still seeing multiple processing emails being sent every 2 minutes.

any other ideas on how multiple emails are being triggered.

**Comment by tn3rb** [comment] 2017-02-22 21:07
can you plz post an example of the $_REQUEST data received from the gateway when this method is hit?
Please remove any sensitive details first though.

**Comment by tn3rb** [comment] 2017-02-22 21:16
Just as an example, here's a list of payment status codes returned from PayPal Standard:

```
'Completed'
'Pending'
'Denied'
'Expired'
'Failed'
'Refunded'
'Partially_Refunded'
'Voided'
'Reversed'
'Canceled_Reversal'
```

whereas the Mijireh gateway only returns:

```
'paid'
'pending'
```

they do not match the payment status codes that EE uses. The gateway you are using is almost certainly using its own status codes that also do not match what EE uses. Let's confirm that out first.

**Comment by jonathanjulian** [comment] 2017-02-22 22:54
so the request data i receive is 

Name	Value
Success	1
TxnType	Purchase
CurrencyInput	NZD
MerchantReference	https://domain.com
TxnData1	full name
TxnData2	email
TxnData3	Race Night: 21-04-2017
AuthCode	008686
CardName	Visa
CardHolderName	NAME
CardNumber	XXXXXXXXX
DateExpiry	0317
CardHolderName	NAME
ClientInfo	xxx.xxx.xxx.xx
TxnId	------
EmailAddress	
DpsTxnRef	xxxxxxxxxxxxxxx
BillingId	
DpsBillingId	
AmountSettlement	60.00
CurrencySettlement	
TxnMac	2BC20210
ResponseText	APPROVED

i receive this on the offsite_page.php where I check that success equals 1 then redirect them to 

https://domain.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=payment_express&uts=XXXX&spco_txn=XXXX&status=PAP

which then i presume triggers the handle_payment_update() function

**Comment by jonathanjulian** [comment] 2017-02-22 22:54
I have had further discussion with payment express and the issue is because they are triggering the  success  url multi times.

so what is happening
1. 
after the customer enters their credit card on payment expresses hosted page they send a request to success on purchase and display their success page.

2.
Event Admin & Primary Registrant payment confirmation emails start send every 2 minutes and the transaction is marked as complete but the registration is still pending payment

3. 
when the user clicks "next" on payment expresses hosted page the user is sent to the success url
at this point all emails are triggered including the payment confirmations emails and the registration is then marked as complete.

**Comment by tn3rb** [comment] 2017-02-23 22:57
@jonathanjulian 
it's hard to know exactly what's going on without seeing all of the code for your entire gateway addon, but the one thing that immediately jumps out as not quite right, is that it appears that you are directing the payment gateway IPN request to this ` offsite_page.php ` page, doing some processing there, and THEN redirecting to:

https://domain.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=payment_express&uts=XXXX&spco_txn=XXXX&status=PAP

The problem with that, is that there is a lot of logic that runs in that second request that is expecting that request to be the actual IPN coming from the gateway. Have you considered moving the logic you perform in ` offsite_page.php ` into the ` handle_payment_update() ` method (and/or other methods in your EE_Offsite_Gateway class) and then allowing EE to direct the IPN to the URL that EE is expecting ?

Your EE_Offsite_Gateway class should have a method called ` set_redirection_info() ` that receives an EE_Payment object that EE uses to record the details of your payment. It is also where you would perform any setup that needs to happen prior to sending the user to the Hosted Pay Page. EE automatically handles setting up the IP that the IPN needs to be directed to:

https://domain.com/registration-checkout/?step=payment_options&action=process_gateway_response&selected_method_of_payment=payment_express&uts=XXXX&spco_txn=XXXX

so that fact that you are somehow receiving the IPNs at this ` offsite_page.php ` page is a bit confusing for us. Bottom line: it appears you are redirecting the IPN to some other URL than where it is intended to be received, and then having troubles with receiving the IPN... ie: EE is expecting the IPN to go to point A, but you have somehow managed to steer it to point B, which of course doesn't appear to be working correctly.

 Is there any chance you can post all of your code somewhere that we could access in order to help you troubleshoot it?

**Comment by nerrad** [comment] 2017-11-04 01:34
I'm going to close this issue because it hasn't been responded to for quite a while.  Feel free to answer the questions and we can reopen if necessary.

**Closed by nerrad** 2017-11-04 01:34 UTC
Labels: gateways, question
