### ISSUE TITLE
Permanently Deleting Auto Draft Events

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3674] opened 2022-01-13 22:05 UTC
Checkout this video: https://www.screencast.com/t/cOw5y4szO

Deleting trashed Auto Draft events: 

-  Branch: `FET/update-event-admin-request-params` , bulk deleting events donesn’t work. Individually deleting events creates a loop.

- Branch: `master` , bulk deleting events creates a loop, individually deleting individual works.

**Comment by garthkoyle** [comment] 2022-01-13 22:06
https://user-images.githubusercontent.com/3094547/149416484-1e0c553f-793a-4d54-a384-179bdfdcfc28.mp4

**Comment by hoseinrafiei** [comment] 2022-01-26 13:27
The issue is fixed in #3689 PR.

**Closed** 2022-02-01 17:05 UTC
Labels: status:triage
