### ISSUE TITLE
Fix eejs console errors

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3772] opened 2022-03-23 16:41 UTC
Using the latest release (and master) versions I'm getting this in the console:

Uncaught TypeError: Cannot set properties of undefined (setting 'eejs')
    at eejs-core.c1e0cebdd6b75e1f4751.dist.js?ver=c1e0cebdd6b75e1f47518e3fa423376e:1:7672
    at eejs-core.c1e0cebdd6b75e1f4751.dist.js?ver=c1e0cebdd6b75e1f47518e3fa423376e:1:7675
(index):443 Uncaught ReferenceError: eejs is not defined
    at (index):443:1

To test just load (apparently) any page, I used the home page of a site.

Look in Dev tools console.

Reports:
https://eventespresso.com/topic/ee-js-errors-in-console/
https://eventespresso.com/topic/console-errors-ee4/
https://eventespresso.com/topic/eejs-not-defined-error/

**Comment by Pebblo** [comment] 2022-04-19 10:34
Reports:
https://eventespresso.com/topic/ee-js-errors-in-console/
https://eventespresso.com/topic/console-errors-ee4/

**Comment by mohdshakeel** [comment] 2022-04-29 09:36
@tony - Which version has this issue? I am not able to reproduce at my local with latest version of plugin.

**Comment by joaovictorangeline** [comment] 2022-04-30 00:00
@Pebblo @mohdshakeel - This issue is present just on EE4 4.10.29.p - this is not happening on 4.10.30.rc.018 (downloadable from our master branch).

**Comment by joaovictorangeline** [comment] 2022-04-30 00:19
Closing this one since it's happening on the Dashboard plugin's page on the v4.10.30, but not on the front end (new issue above). Already forwarded the v4.10.30 to the customer.

**Comment by Pebblo** [comment] 2022-05-01 09:50
@joaovictorangeline this is indeed happening for me on the front end using master branch.

Home page - https://monosnap.com/file/hU87zjiKmKN5Vgbopr26J43qK3MmYk
Random Page - https://monosnap.com/file/NYS0BAipl51GCE2TPB5f9N2VRVpwZB

It is also happening for customers, so until this has been confirmed fixed on the front end please leave the ticket open.

Just for future reference, if it has/had of been fixed in master it would of been good to confirm how it was fixed and include this ticket in the change log, especially because customers are posting about the issue, so its need a change log item to show its fixed.

**Comment by joaovictorangeline** [comment] 2022-05-01 17:36
@Pebblo Could you please share the following?
- Version of Event Espresso:
- Version of WordPress:
- Browser 
- PHP Version

Thanks!

**Comment by joaovictorangeline** [comment] 2022-05-01 17:38
Just to add that's is also displayed on Dashboard's plugins page:
![image](https://user-images.githubusercontent.com/102395051/166157559-f2f5e6e1-2ec8-4dcb-808f-1b787d51be4b.png)

**Comment by Pebblo** [comment] 2022-05-02 08:45
- Version of Event Espresso: 4.10.30.rc.018
- Version of WordPress: 5.9.3 (this should **always** be latest version, or the beta version)
- Browser: Chrome (latest)
- PHP Version: tested 7.3.7 & 7.4.29

**Comment by joaovictorangeline** [comment] 2022-05-02 23:05
I am running the following:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/102395051/166340141-92c6cd38-83ad-4fab-bbbc-6213e0a7920b.png">
And not able to reproduce the console errors on the front end, just on the plugin's page. Which WordPress theme you are currently using? Also, can you share your current activated plugins?

**Comment by Pebblo** [comment] 2022-05-03 09:56
I've tested using Twenty Fifteen, Twenty Seventeen, Twenty Twenty and a few random themes I have installed on this site, I don't think this is a theme/plugin conflict.

I get exactly the same issue with just Event Espresso 4 core active using a default twenty* theme.

**Comment by christophhapple** [comment] 2022-05-12 09:11
Having the same issue. Any ETA on this?

**Comment by tn3rb** [comment] 2022-05-12 21:40
looks like it was introduced in 4.10.27.p by https://github.com/eventespresso/event-espresso-core/commit/683aea85d83f3cb94a3902b10fdc985f16d90337

**Comment by joaovictorangeline** [comment] 2022-05-14 02:47
> I've tested using Twenty Fifteen, Twenty Seventeen, Twenty Twenty and a few random themes I have installed on this site, I don't think this is a theme/plugin conflict.
> 
> I get exactly the same issue with just Event Espresso 4 core active using a default twenty* theme.

@Pebblo Can you test the new changes included in @tn3rb PR? I have tested and did not find any errors.

**Comment by Pebblo** [comment] 2022-05-16 09:53
Thanks @tn3rb!

This does fix the issue but it fails unit tests, can you check those out, please?

**Comment by tn3rb** [comment] 2022-05-16 20:43
new fixes pushed that correct unit tests

**Closed** 2022-05-23 19:54 UTC
