### ISSUE TITLE
Use of undefined constant TICKET_SELECTOR_ASSETS_URL, TICKET_SELECTOR_TEMPLATES_PATH

### ISSUE THREAD

**Issue by PunchRockgroin** [eventespresso/event-espresso-core#199] opened 2017-01-26 23:15 UTC
### Is this a bug report?

* [ x] yes
* [ ] no

### What branch did this occur in?
Event Espresso - 4.9.27.p

### What version of WordPress is on the site this issue happened?
Version 4.7.2 
PHP 7.0.15-1+deb.sury.org~xenial+1 

### Outline the steps to reproduce
Try to add a registration to any event through the back end or front end. This results in a blank form.

Debug log says:
`[26-Jan-2017 22:59:47 UTC] PHP Notice:  Use of undefined constant TICKET_SELECTOR_ASSETS_URL - assumed 'TICKET_SELECTOR_ASSETS_URL' in /var/www/xxxxxxx/wp-content/plugins/event-espresso-core-reg/modules/ticket_selector/EED_Ticket_Selector.module.php on line 224

[26-Jan-2017 22:59:47 UTC] PHP Notice:  Use of undefined constant TICKET_SELECTOR_ASSETS_URL - assumed 'TICKET_SELECTOR_ASSETS_URL' in /var/www/xxxxxxx/wp-content/plugins/event-espresso-core-reg/modules/ticket_selector/EED_Ticket_Selector.module.php on line 227

[26-Jan-2017 22:59:47 UTC] PHP Notice:  Use of undefined constant TICKET_SELECTOR_TEMPLATES_PATH - assumed 'TICKET_SELECTOR_TEMPLATES_PATH' in /var/www/xxxxxxx/wp-content/plugins/event-espresso-core-reg/modules/ticket_selector/TicketDetails.php on line 166

[26-Jan-2017 22:59:47 UTC] PHP Notice:  Use of undefined constant TICKET_SELECTOR_TEMPLATES_PATH - assumed 'TICKET_SELECTOR_TEMPLATES_PATH' in /var/www/xxxxxxx/wp-content/plugins/event-espresso-core-reg/modules/ticket_selector/TicketDetails.php on line 166

[26-Jan-2017 22:59:47 UTC] PHP Notice:  Use of undefined constant TICKET_SELECTOR_TEMPLATES_PATH - assumed 'TICKET_SELECTOR_TEMPLATES_PATH' in /var/www/xxxxxxx/wp-content/plugins/event-espresso-core-reg/modules/ticket_selector/TicketDetails.php on line 166

[26-Jan-2017 22:59:47 UTC] PHP Notice:  Use of undefined constant TICKET_SELECTOR_TEMPLATES_PATH - assumed 'TICKET_SELECTOR_TEMPLATES_PATH' in /var/www/xxxxxxx/wp-content/plugins/event-espresso-core-reg/modules/ticket_selector/TicketSelectorStandard.php on line 129`

Quick Fix was to hardcode those values into the specific lines i.e. 
`wp_register_style('ticket_selector', plugin_dir_url( __FILE__ ) . 'assets' . DS . 'ticket_selector.css');`

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
https://www.dropbox.com/s/d7hpehq9pd17h8j/image.png

**Comment by nerrad** [comment] 2017-01-27 14:06
I can confirm things are broken for manual registration in the admin dashboard.  However, registration is working fine for me via the frontend.  I've created an internal ticket to fix this (https://events.codebasehq.com/projects/event-espresso/tickets/10432).

**Comment by nerrad** [comment] 2017-01-27 14:49
We just merged a fix into the master branch for the ticket selector in the admin side registration process and it's being packaged for release now.  Thanks for reporting!

I realize you mentioned in here that registrations weren't working for you on the frontend either, the issue fixed here doesn't have anything to do with registrations on the frontend and our team was unable to reproduce issues there so its likely something different happening in your case.  Can you create another ticket describing what's happening for you on the front-end?  Make sure you include specifics about your install (eg, what other EE add-ons are active an in use).

**Closed by nerrad** 2017-01-27 14:49 UTC
Labels: bug
