### ISSUE TITLE
Attendee Mover and PRIMARY_REGISTRANT_ANSWER_* error

### ISSUE THREAD

**Issue by daragh99** [eventespresso/event-espresso-core#221] opened 2017-03-21 00:30 UTC
### Is this a bug report?

* [ x] yes
* [ ] no

### What branch did this occur in?
4.9.x

### What version of WordPress is on the site this issue happened?
4.7.3

### Outline the steps to reproduce

Hi there,
I tracked down what I think is a bug you might be interested in.
Scenario: we use [PRIMARY_REGISTRANT_ANSWER_*] to (a) send emails to a person other than the attendee (b) in the body of message templates.

The bug manifests itself in registrations that have been moved by the attendee mover. When we choose to manually resend moved registrations via the Registrations screen (after a moved email), we noticed blanks where the answers to the questions should have been substituted.

Tracing the code, I found the problem to be a lookup in
core/libraries/shortcodes/EE_Primary_Registration_Details_Shortcodes.lib.php

The problem shows up in this snippet:
$primary_registration->registrations[$primary_reg->ID()]
$primary_registration is assigned (correctly) to the “new” registration that is created for the moved attendee. $primary_reg appears to be the “old” registration (i.e. the one that was cancelled when moving the attendee).

Further digging revealed that the objects are created in
core/libraries/messages/data_class/EE_Messages_incoming_data.core.php
This calls EE_Transaction->primary_registration

The problem appears to be in the body of the primary_registration() function, which uses the get_first_related mapping in the object model. In this case, it should be something like primary_active_registration – as first_related returns the previous, cancelled registration – causing the lookup failure in the first line of code above.

I fixed this issue by:

- Added a primary_active_registration function to EE_Transaction
- Editing EE_Messages_incoming_data to use the new function (which I feel might have side effects I don’t understand yet – probably they’ll reveal themselves)

This doesn’t matter in when parsing other PRIMARY_REGISTRANT fields because they map to method calls on an object that is correctly populated.

My guess is that the real solution is to make the get_first_related call do an order-by primary key descending, but I’ve no idea what effect this might have.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

n/a

### Please include any links to the page(s) demonstrating this issue (if possible).

n/a

**Comment by nerrad** [comment] 2017-03-21 11:44
Thanks for reporting this, we'll investigate.

**Comment by nerrad** [comment] 2017-03-21 11:48
Did the registrations you moved include the "primary registrant" from one transaction?

**Comment by nerrad** [comment] 2017-03-21 11:51
Also, 

> The bug manifests itself in registrations that have been moved by the attendee mover. When we choose to manually resend moved registrations via the Registrations screen (after a moved email), we noticed blanks where the answers to the questions should have been substituted.

Questions are attached to question groups which in turn are attached to events. Were the questions attached to `[PRIMARY_REGISTRANT_ANSWER_*]` in your message template asked in the event you moved your registrations to?  If not, that could explain the resulting emails being blank.

**Comment by nerrad** [comment] 2017-03-21 11:54
Internal ticket: https://events.codebasehq.com/projects/event-espresso/tickets/10608

**Comment by tn3rb** [comment] 2017-03-21 20:37
@daragh99 

if you like, you can try this branch:
https://github.com/eventespresso/event-espresso-core/tree/BUG-10608-primary-registration-query
to see if it fixes the issue for you.
you would need to revert your changes to the messages system as the problem is definitely due to the usage of get_first_related() within \EE_Transaction::primary_registration() as you have pointed out.

**Comment by daragh99** [comment] 2017-03-21 21:53
Thanks Darren. Glad to hear we were on the right track. We're actually
using a modified version of 4.9.16.p - we changed some behaviour of the
SPCO on the front-end, and wrote further modifications to the messages
systems to control when certain messages were sent based on ticket type -
I'll have a look at your bugfix branch and incorporate the changes to our
own work.

Daragh

On Wed, Mar 22, 2017 at 7:37 AM, Brent Christensen <notifications@github.com

**Comment by nerrad** [comment] 2017-03-21 21:57
It would be to your benefit if instead of directly modifying the code you used existing action/filter hooks to add in custom logic.  If hooks aren't found where needed, you could submit a pull request with what you need and we could look into adding them into the core code for you.

**Comment by daragh99** [comment] 2017-03-21 22:00
Yes indeed, it has definitely felt a bit less than ideal, but the clients
I'm working with are very particular. I'll bear that in mind about hooks,
it's a great suggestion.

Daragh

**Comment by tn3rb** [comment] 2017-06-23 15:44
closing issue as this fix has been released as part of 4.9.38

**Closed by tn3rb** 2017-06-23 15:44 UTC
Labels: bug, messages

**Comment by daragh99** [comment] 2017-06-23 21:11
Thanks!
